#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#


library(shiny)
library(ggplot2)
library(wordcloud)
library(plotly)
library(dplyr)
library(tidytext)
library(tidyr)
library(reshape2)
library(RColorBrewer)

moon_text<-readRDS("moon_text.rds")
sun_text<-readRDS("sun_text.rds")
bing_word_counts_moon<-readRDS("bing_word_counts_moon.rds")
bing_word_counts_sun<-readRDS("bing_word_counts_sun.rds")
moonpoints<-readRDS("moonpoints.rds")
sunpoints<-readRDS("sunpoints.rds")
map.data <- map_data("state")


ui<-fluidPage(titlePanel(fluidRow(
  column(8, 
         h3("MA615 Twitter Project"),
         h6("Presented by Yaqi. 
            All the data and codes are accessible on", a(href="https://github.com/huangyaqi9525", "huangyaqi9525 Github"))
         ))),
  navbarPage(title= "",
             tabPanel("Introduction",
                      hr(),
                      p("The topic I have chosen for the final project is about a game which I have
been playing recently, which is called Pokémon Ultra Moon. 
The publisher The Pokémon Company always launch two versions 
of game when the new game is released, for example, 
in this case would be Pokémon Ultra Moon and Pokémon Ultra Sun. 
They provide different legendary pokémon for different versions. 
The version I purchased was Pokémon Ultra Moon. 
For thie project, I am interested in the followings:
- what is the overall response of this new game from the players using twitter."),

                        p("- Is there any difference in comments between Pokémon Ultra Moon and Pokémon Ultra Sun."),
                        
                        p("- Is there any of the difference corresponds to the region?"),
                        
                        p("To answer the above, I have conducted the following technics:"),
                        
                        p("- Sentimemt Analysis"),
                        
                        p("- Wordcloud"),
                        
                        p("- Mapping")
                        ),
       
             tabPanel("Maps",
                      h4("Places where people tweete about Pokémon Ultra Moon & Pokémon Ultra Sun"),
                      p("We could conclude the similar results from the map for Pokémon Ultra Moon and Pokémon Ultra Sun
                        that most of the twittes were generated from the east of the State, 
                        and there are also lots of twittes generated from the west boundary of 
                        the landscape."),
                      hr(),
                      sidebarLayout(
                        sidebarPanel(
                          selectInput(inputId = "mapinput",
                                      label="Select a Game",
                                      choices = c("Pokémon Ultra Moon","Pokémon Ultra Sun"))
                        ),
                        mainPanel(plotOutput("maps"))
                      )
                      ),
       
             
             tabPanel("Sentiment",
                      h4("Sentiment Analysis"),
                      p("From the above two wordcloud plots, we could clearly 
                        see that both Moon and Sun version sharing the 
                        same comments for both positive and negative sentiments. 
                        And the proportion for the top10 most generated word 
                        for both postive and negative sentiments for both Moon
                        and Sun versions are pretty similar. For example, 
                        the word Shiny shares the biggest proportion 
                        for both the Moon and Sun on the positive side, 
                        and the word Showdown shares the biggest proportion 
                        for the both versions on the negative sides."),
                      hr(),
                      sidebarLayout(
                        sidebarPanel(selectInput(inputId = "sentiinput",
                                                 label="Select a Game",
                                                 choices = c("Pokémon Ultra Moon","Pokémon Ultra Sun"))
                        ),
                        mainPanel(plotOutput("sentiment")))
                      ),
             
             tabPanel("Wordcloud",
                      h4("Text analysis for Pokémon Ultra Moon & Pokémon Ultra Sun"),
                      p("We could get same conclusion from the sentiment analysis of 
Pokémon Ultra Sun, that more positive comments were generated by the users on twitter.

                       However, there is a slightly difference in the number of 
                        positive and negative between Moon and Sun, that the positive 
                        comments for the Moon version might be slightly greater than 
                        the Sun version."),
                      sidebarLayout(
                        sidebarPanel(
                          selectInput(inputId = "wordinput",
                                      label="Select a Game",
                                      choices = c("Pokémon Ultra Moon","Pokémon Ultra Sun"))
                       ),
                        mainPanel(
                          plotOutput("wordcloud")
                        )
                      )
             )
)

)


#server
server<-function(input, output){
  
  
  ### maps
  output$maps<-renderPlot({
    if(input$mapinput=="Pokémon Ultra Moon"){
      ggplot(map.data) + 
        geom_map(aes(map_id = region),  
                 map = map.data,  
                 fill = "white",             
                 color = "grey20", size = 0.25) + 
        expand_limits(x = map.data$long, y = map.data$lat) +            
        theme(axis.line = element_blank(),  
              axis.text = element_blank(),  
              axis.ticks = element_blank(),                     
              axis.title = element_blank(),  
              panel.background = element_blank(),  
              panel.border = element_blank(),                     
              panel.grid.major = element_blank(), 
              plot.background = element_blank(),                     
              plot.margin = unit(0 * c( -1.5, -1.5, -1.5, -1.5), "lines")) +  
        geom_point(data = moonpoints,             
                   aes(x = x, y = y), size = 1,  
                   alpha = 1/5, color = "red")+labs(title="Map for Pokémon Ultra Moon")
    }
    else{
      ggplot(map.data) + 
        geom_map(aes(map_id = region),  
                 map = map.data,  
                 fill = "white",             
                 color = "grey20", size = 0.25) + 
        expand_limits(x = map.data$long, y = map.data$lat) +            
        theme(axis.line = element_blank(),  
              axis.text = element_blank(),  
              axis.ticks = element_blank(),                     
              axis.title = element_blank(),  
              panel.background = element_blank(),  
              panel.border = element_blank(),                     
              panel.grid.major = element_blank(), 
              plot.background = element_blank(),                     
              plot.margin = unit(0 * c( -1.5, -1.5, -1.5, -1.5), "lines")) +  
        geom_point(data = sunpoints,             
                   aes(x = x, y = y), size = 1,  
                   alpha = 1/5, color = "blue")+labs(title="Map for Pokémon Ultra Sun")
    }
  }
  )
  
  
  ##sentiment
  output$sentiment<-renderPlot({
    if(input$sentiinput=="Pokémon Ultra Moon"){
      bing_word_counts_moon %>%
        group_by(sentiment) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = sentiment)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~sentiment, scales = "free_y") +
        labs(y = "Contribution to sentiment",
             x = NULL) +
        coord_flip()
    }
    else{
      bing_word_counts_sun %>%
        group_by(sentiment) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = sentiment)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~sentiment, scales = "free_y") +
        labs(y = "Contribution to sentiment",
             x = NULL) +
        coord_flip()
    }
  }
  )
  
  ##word cloud
  output$wordcloud<-renderPlot({
    if(input$wordinput=="Pokémon Ultra Sun"){
      moon_text %>%
        inner_join(get_sentiments("bing")) %>%
        count(word, sentiment, sort = TRUE) %>%
        acast(word ~ sentiment, value.var = "n", fill = 0) %>%
        comparison.cloud(colors = c("#F8766D", "#00BFC4"),
                         max.words = 100,title.size=2)
    }
    else{
      sun_text %>%
        inner_join(get_sentiments("bing")) %>%
        count(word, sentiment, sort = TRUE) %>%
        acast(word ~ sentiment, value.var = "n", fill = 0) %>%
        comparison.cloud(colors = c("#F8766D", "#00BFC4"),
                         max.words = 100,title.size=2)
    }
  }
  )
}
# Run the application 
shinyApp(ui = ui, server = server)